-- Bind only script mappings confirmed by the current SkyFire or Emucoach reference DB.
-- Existing SmartAI and existing ScriptName implementations are deliberately preserved.
START TRANSACTION;
INSERT IGNORE INTO `areatrigger_scripts` (`entry`,`ScriptName`) VALUES (8750,'AreaTrigger_at_msv_engine_of_nalaksha');
INSERT IGNORE INTO `areatrigger_scripts` (`entry`,`ScriptName`) VALUES (9278,'AreaTrigger_at_soo_forward_korkron_cage_prisoners');
INSERT IGNORE INTO `areatrigger_scripts` (`entry`,`ScriptName`) VALUES (9352,'AreaTrigger_at_soo_forward_korkron_barracks');
INSERT IGNORE INTO `areatrigger_scripts` (`entry`,`ScriptName`) VALUES (9353,'AreaTrigger_at_soo_forward_korkron_skullsplitter');
UPDATE `creature_template` SET `ScriptName`='npc_ring_valiants' WHERE `entry`=33285 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_ring_valiants' WHERE `entry`=33306 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_ring_valiants' WHERE `entry`=33382 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_ring_valiants' WHERE `entry`=33383 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_ring_valiants' WHERE `entry`=33384 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_barrent_wounded_defender' WHERE `entry`=38805 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_azshara_awol_grunt' WHERE `entry`=42646 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_stranglethorn_priestess_hurala' WHERE `entry`=42812 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_stranglethorn_emerine' WHERE `entry`=43885 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_twilight_firebeads_patrol' WHERE `entry`=46849 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_deadmines_prototype_reaper' WHERE `entry`=49208 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_prince_anduin_decision_helpers' WHERE `entry`=54620 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_adolescent_mushan' WHERE `entry`=56239 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_wyrmhorn_turtle' WHERE `entry`=56256 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_lupello' WHERE `entry`=56357 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_jade_forest_instant_message_camera_bunny' WHERE `entry`=56412 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_snagtooth_hooligan' WHERE `entry`=56462 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_prince_anduin_decision' WHERE `entry`=56485 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_prince_anduin_decision_helpers' WHERE `entry`=56486 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_prince_anduin_decision_helpers' WHERE `entry`=56487 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_prince_anduin_decision_helpers' WHERE `entry`=56488 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_frenzyhop' WHERE `entry`=56514 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_jf_wild_prowler' WHERE `entry`=56653 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_jf_wild_stalker' WHERE `entry`=56683 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_hornbill_strider' WHERE `entry`=56753 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_achiev_prisoned_sha' WHERE `entry`=56766 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_jade_forest_playful_colored_serpent' WHERE `entry`=56850 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_jade_forest_playful_colored_serpent' WHERE `entry`=56851 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_jade_forest_playful_colored_serpent' WHERE `entry`=56852 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_jade_forest_playful_colored_serpent' WHERE `entry`=56853 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_grainhunter_hawk' WHERE `entry`=57215 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_grainhunter_hawk' WHERE `entry`=57216 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_springtail_gnasher' WHERE `entry`=57413 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_mothfighter' WHERE `entry`=57648 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_unbarreled_pandaren' WHERE `entry`=57681 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_achiev_prisoned_sha' WHERE `entry`=58201 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_wildscale_herbalist' WHERE `entry`=58216 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_ikthik_vanguard' WHERE `entry`=58368 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_darkhide' WHERE `entry`=58435 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_veb_shado_pan_trainee' WHERE `entry`=58992 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_barrel_of_fireworks' WHERE `entry`=59284 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_kunlai_old_poof_poof' WHERE `entry`=60015 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_broketooth_leaper' WHERE `entry`=60742 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_broketooth_leaper' WHERE `entry`=60744 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_silverback_piker' WHERE `entry`=60746 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_ooking_shaman' WHERE `entry`=60752 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_lorewalker_cho_peering_into_past' WHERE `entry`=63307 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_vfw_krungko_fingerlicker' WHERE `entry`=64389 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_pandaren_firework_launcher' WHERE `entry`=65934 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_darkhatched_shaman' WHERE `entry`=67255 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_darkhatched_oracle' WHERE `entry`=67256 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_darkhatched_skulker' WHERE `entry`=67257 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_darkhatched_skinflayer' WHERE `entry`=67258 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_darkhatched_flesh_hunter' WHERE `entry`=67259 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_darkhatched_lizard_lord' WHERE `entry`=67263 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_broodmaster_noshi' WHERE `entry`=67264 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_rakgor_bloodrazor' WHERE `entry`=67266 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_voljin' WHERE `entry`=67414 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_little_patience_faction_leader' WHERE `entry`=67569 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_mogu_rune' WHERE `entry`=67686 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_goblin_cannon' WHERE `entry`=67694 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_spring_saurok_slayer' WHERE `entry`=67706 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_stalactite' WHERE `entry`=67755 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_grizzle_gearslip' WHERE `entry`=67782 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_corrupted_dark_hatched_egg' WHERE `entry`=67798 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_corrupted_darkhatched_slayer' WHERE `entry`=67832 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_broken_mogu_tablet' WHERE `entry`=67862 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_dagger_in_dark_broken_mogu_tablet' WHERE `entry`=67863 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_little_patience_faction_leader' WHERE `entry`=67883 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_little_patience_muckmaw_crocolisk' WHERE `entry`=67922 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_little_patience_bogrot' WHERE `entry`=67974 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_little_patience_faction_leader' WHERE `entry`=68057 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_little_patience_wakened_mogu' WHERE `entry`=68102 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_little_patience_faction_leader' WHERE `entry`=68240 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_little_patience_spirit_bomb' WHERE `entry`=68296 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_little_patience_krasari_stalker' WHERE `entry`=68348 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_little_patience_commander_scargash' WHERE `entry`=68474 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_little_patience_faction_leader' WHERE `entry`=68599 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_little_patience_riverblade_marauder' WHERE `entry`=68775 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_little_patience_swamp_gas' WHERE `entry`=68816 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_little_patience_king_varian_wrynn' WHERE `entry`=69026 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_zandalari_beastcaller_passenger' WHERE `entry`=69397 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_willy_wilder' WHERE `entry`=70126 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_kun_lai_grandpa_grumplefloot' WHERE `entry`=71082 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_golden_lotus_trigger' WHERE `entry`=71684 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_golden_lotus_trigger' WHERE `entry`=71686 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_golden_lotus_trigger' WHERE `entry`=71711 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_siege_of_orgrimmar_theramore_prisoners' WHERE `entry`=72498 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_thok_monstrous_gastropod' WHERE `entry`=73164 AND `ScriptName`='' AND `AIName`='';
UPDATE `creature_template` SET `ScriptName`='npc_tears_of_the_vale' WHERE `entry`=73638 AND `ScriptName`='' AND `AIName`='';
UPDATE `gameobject_template` SET `ScriptName`='go_containment_override' WHERE `entry`=213457 AND `ScriptName`='' AND `AIName`='';
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (1126,'spell_dru_mark_of_the_wild_stats');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (1459,'spell_mage_arcane_brilliance_stats');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (1463,'spell_mage_incanters_absorbtion_manashield');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (5225,'spell_dru_glyph_of_the_predator');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (6962,'spell_warl_glyph_of_felguard_loading');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (11426,'spell_mage_incanters_absorbtion_absorb');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (12975,'spell_warr_last_stand');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (19263,'spell_hunt_glyph_of_deterrence');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (19740,'spell_pal_blessing_of_might');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (20217,'spell_pal_blessing_of_kings');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (20271,'spell_pal_sword_of_light_damage_bonus_holy');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (21562,'spell_pri_power_word_fortitude_stats');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (23218,'spell_dru_shapeshift_move_speed');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (24275,'spell_pal_sword_of_light_damage_bonus_holy');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (30146,'spell_warl_glyph_of_felguard');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (49222,'spell_dk_t15_blood_4p_bonus');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (56241,'spell_warl_glyph_of_verdant_spheres');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (61316,'spell_mage_dalaran_brilliance');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (85372,'spell_rescue_survivor_quest');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (93844,'spell_shadowfang_unholy_empowerment');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (111898,'spell_warl_glyph_of_felguard');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (112870,'spell_warl_glyph_of_felguard');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (113399,'spell_scarlet_halls_archery_target_vehicle_override_eff');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (113436,'spell_scarlet_halls_heroic_defense');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (113862,'spell_mage_greater_invisibility_damage_reduction');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (114280,'spell_dru_glyph_of_the_predator');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (114877,'spell_scarlet_halls_archery_target_vehicle_override');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (114889,'spell_sha_stone_bulwark_totem_passive');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (116267,'spell_mage_incanters_absorbtion_absorb');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (116860,'spell_warl_ember_test');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (117006,'spell_devastating_arc');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (119392,'spell_monk_charging_ox_wave');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (119985,'spell_sha_of_fear_dread_spray_fear');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (122503,'spell_unsok_burning_amber_triggering');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (122853,'spell_inhale');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (125084,'spell_monk_charging_ox_wave_visual');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (133311,'spell_little_patience_faction_construction_progress');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (133461,'spell_little_patience_inspired_jinyu');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (133494,'spell_little_patience_terrified');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (133798,'spell_drain_life_damage');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (133849,'spell_little_patience_faction_construction_progress');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (133852,'spell_little_patience_construction_bar_movement');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (133928,'spell_little_patience_inspired_gnome');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (134086,'spell_little_patience_faction_construction_progress');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (134116,'spell_little_patience_inspired_dwarf');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (134567,'spell_little_patience_faction_construction_progress');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (135260,'spell_little_patience_faction_construction_progress');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (135414,'spell_little_patience_inspired_night_elf');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (136929,'spell_thok_summon_ice_tomb');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (140809,'spell_waterspout_aura');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (144318,'spell_mage_incanters_absorbtion_manashield');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (145096,'spell_garrosh_touch_of_yshaarj_player_launcher');
INSERT IGNORE INTO `spell_script_names` (`spell_id`,`ScriptName`) VALUES (148467,'spell_hunt_glyph_of_deterrence');

-- Build 18414 does not contain the legacy Divine Storm heal spells 54171/54172.
DELETE FROM `spell_script_names` WHERE `spell_id`=53385 AND `ScriptName`='spell_pal_divine_storm';
COMMIT;
